project:
  type: website
  output-dir: docs

website:
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/feinmann/blog2310
  favicon: profile.jpg
  comments:
    giscus: 
      repo: feinmann/blog2310

format:
  html:
    theme: default
    css: styles.css



