project:
  type: website
  output-dir: docs

website:
  title: "blog2310"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/feinmann/blog2310
  favicon: profile.jpg

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



