project:
  type: website
  output-dir: docs

website:
  title: "blog2310"
  repo-url: https://github.com/feinmann/blog2310
  issue-url: https://github.com/feinmann/blog2310/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/feinmann/blog2310
  favicon: profile.jpg
  comments:
    giscus: 
      repo: feinmann/blog2310
  page-footer:
    border: false
    background: light
    # following works only with quarto extention `now` by Garrick Aden-Buie
    # https://pkg.garrickadenbuie.com/quarto-now/
    left: >- 
       © {{< now year >}} 3atthias 3erger 
    right: >-
      Made with 💙  
    
format:
  html:
    theme:
      light: default
    css: styles.css
    code-copy: true
    code-overflow: wrap

filters:
  - auto-dark

